### ISSUE TITLE
Binary broadcast error

### ISSUE THREAD

**Issue by andreasnoack** [andyferris/TransposedVectors.jl#2]
Something weird is happening here
```jl
julia> x = complex(randn(5), randn(5))
5-element Array{Complex{Float64},1}:
   2.44132+2.50511im
  -1.14645-0.273445im
  0.472802-0.292263im
 -0.578785-0.119831im
  0.101981+1.3076im

julia> imag.(diag(x .+ x'))
5-element Array{Float64,1}:
  0.0
 -0.273445
 -0.292263
 -0.119831
  1.3076
```

**Comment by andyferris** [comment]
OK - that is *odd*. Certainly, something strange is happening in `broadcast`.

**Comment by andyferris** [comment]
I've been looking for half an hour, and I can't see where [this code in Base](https://github.com/JuliaLang/julia/blob/release-0.5/base/broadcast.jl#L116L132) is getting confused.

Do you have any insight?

**Comment by andyferris** [comment]
Right, I figured it out. My approach wasn't compatible with the `CartesianIndex` scheme. I can fix this

**Comment by andyferris** [comment]
Now `CartesianIndex{2}` is supported. In general, we need to support higher-dimensional Cartesian indices (though I wish that were fixed in `broadcast`, etc, instead).

**Comment by andreasnoack** [comment]
It might make sense to see if this should be fixed in the Cartesian code. My feeling is that it might be possible that this could "just work" if the underlying code was written in the right way and that it would be better than working around it here. However, he cartesian code gives me a headache so I'm not sure I'm able to easily identify what should be changed.

**Comment by andyferris** [comment]
Ah, I'm not sure there's any ability for `Cartesian` to anticipate or even react to [this line of code](https://github.com/andyferris/TransposedVectors.jl/blob/master/src/TransposedVector.jl#L47).

However, there are a two practical things that could be done to make this stuff easier for an array implementer like me:

 - Never give `CartesianIndex` to objects that are `LinearFast` from functions in `Base`. I really wasn't expecting this.
 - Disallow trailing ones in `CartesianIndex` (and even standard indexing!), and fix `broadcast` appropriately. Or at the very least don't create trailing ones from functions in `Base`.
